berkerpeksag/astor

.travis.yml

Travis CI's container based infra allows faster builds as it allows
caching, here change is made to use wheels and cache them so that
downloads do not hit the network once cached. Though the first build
takes a bit of time, subsequent builds should be effectively able to use
the build cache and do faster builds

run travis in containers!

---

astor/misc.py
setup.py
tests/test_codegen.py
tests/test_misc.py

This came up while working on a momentarily forthcoming pull request (the topic of which can be easily inferred) for Hy.

add support for Python 3.5 infix matrix multiplication

---

.gitignore
astor/codegen.py
tests/test_codegen.py

This pull request proposes of implementation of support in astor for two new-in-Python 3.5 syntactic features, namely [additional unpacking generalizations](https://www.python.org/dev/peps/pep-0448/) and [coroutines with async and await syntax](https://www.python.org/dev/peps/pep-0492/). Also, it is proposed that code-generation for dictionary literals not include a trailing comma and space, to better reflect most actual Python code.
Developed against python/cpython@c4766cf152.

Python 3.5 iterable unpacking and async syntax; idiomatic dictionary literals

---

astor/codegen.py
tests/test_codegen.py

This really ought to have been part of #19, but the author of that pull request would seem to have forgotten it.
(Also, a confession: I was also going to add a test for the new way to use iterable unpacking in expressions like this—
``` python
def test_right_hand_side_iterable_unpacking(self):
source = textwrap.dedent("""\
one_to_ten = [*range(1, 8), 8, 9, 10]""")
self.assertAstSourceEqualIfAtLeastVersion(source, (3, 5))
```
But then it turns out that this doesn't pass on all Python versions for the "spurious" reason that on Python >=3.0 but <=3.4, while trying to *run* that source code does raise a `SyntaxError`, merely calling `ast.parse` on it (as our `assertAstSourceEqualIfAtLeastVersion` test helper does) does *not*, one imagines because `Starred(value=Call(func=Name(id='range', …

non-call dictionary unpacking

---

astor/codegen.py
tests/test_codegen.py

It turns out the cheezy way I did yield fixes before was no good, because
it is legal to do (yield foo)(bar).
The new way always encloses yield statements in parentheses.  This is ugly,
and MAY not (I don't know) work on earlier versions, although it works fine
on 2.7.
So it fixes a known bug (behavior actually occurs in a library), but might break < 2.7.  Probably the right thing to do for now.

Yield fixes

---

astor/code_gen.py
astor/string_repr.py
tests/test_code_gen.py

Reduce the number of strings that get triple-quoted by the new pretty printing logic.
It was fairly aggressive at triple-quoting.  In general, we do not want to triple-quote strings embedded in lists unless they have line feeds in them.

Stop triple quoting strings embedded in function calls

---

.gitignore
astor/code_gen.py
astor/op_util.py
tests/test_code_gen.py

This pull request proposes the addition of two entries to the operator precedence table, and use of the `delimit` context manager in `visit_Await`, to avert errors observed with Python 3.5 (a failing unit test, and a file in the Python source tree failing to roundtrip with `astor.rtrip`).

precedence for `await` and `async for`

---

astor/__init__.py
tests/test_code_gen.py

DeprecationWarnings don't appear by default, so I used FutureWarning to insure it shows up.
If this is wrong, we can change.

Deprecate old API (issue #59)

---

tests/test_code_gen.py

-  We already pass these, but some other unparsers don't,
so it's worth adding them to the regression.

Add slicing tests

---

astor/__init__.py
tests/test_code_gen.py

- Change to DeprecationWarning to reduce noise in other testers
- Set stack level so warning appears with proper source line
- Check for warning in test

Fix new deprecation warnings

---

astor/__init__.py
astor/code_gen.py
astor/file_util.py
astor/node_util.py
astor/rtrip.py
astor/source_repr.py
astor/string_repr.py
astor/tree_walk.py
tests/build_expressions.py
tests/check_expressions.py
tests/test_code_gen.py
tests/test_misc.py

- Algorithmic gains in pretty printer
- Huge gains from using lists instead of generators in string prettifier
- Diminishing gains from a few closures in code_gen
- One code-gen fix (and a test case) for None leaking into code-gen result list.
- Even larger gains to be had in node_util for tree scrubbing, etc., but not now
Overall, when running rtrip on the 3.6 stdlib, this reduces the time spent in code generation by 40%, for an overall gain of 23%.  There is lots of room for improvement in node_util (for the scrubbing, comparison, and dumping, not for the code generation), but I'm not willing to do that at the moment.
**edited**:  Found even more gains in the strings, and created a fast comparison in node_util for rtrip.  rtrip is much faster now.

Enhance code generator performance

---

tests/check_astunparse.py
tests/test_code_gen.py
tests/test_misc.py
tests/test_optional.py

- Make it easier to test against other packages
These change allows `to_source` to be replaced and tests to be run, and conversely allow ease of running our tests against other packages.  This was tested with the astunparse package.
I need to do PEP8 cosmetic changes before we merge.

Refactor tests

---

README.rst

The domain astor.rtfd.org doesn't matched the certificate that is being served. so the documentation link resulted in a browser warning, rather than the docs.

Link to Read The Docs with working SSL

---

.travis.yml
AUTHORS
astor/code_gen.py
docs/changelog.rst
tests/test_code_gen.py
tox.ini

If an f-string was ended with a newline character (more precisely, if
the last element of a JoinedStr node was just a newline character), its
round-trip source code representation would have an extra newline on a
wrong place, resulting in invalid syntax.
The bug affects only python>=3.6 (f-strings weren't supported before)
This commit fixes the aforementioned bug.
Fixes #89.

Fix trailing newlines in f-strings

---

.travis.yml
astor/code_gen.py
docs/changelog.rst

Closes #106.
I tested this on CPython commit 1d419faccdaae27d968cef1e1ece6b9374694573.

Revert Python 3.7 docstring handling

---

.travis.yml

Added Python 3.8-dev to Travis to check the compatibility issues with the next version of Python

Added 3.8-dev to Travis

---

AUTHORS
astor/code_gen.py
astor/source_repr.py
docs/changelog.rst
tests/test_code_gen.py

When looping over a joined str, if a node is ast.Str and the value is
just a newline "\n", the write() function adds an additional indentation
after it, which fails to represent the original string. By calling
self.result.append() here directly the issue is resolved.
The added test could show the issue. With code_gen unmodifed, it fails
with the following error:
```
AssertionError: "if 1:\n    x = f'{host}\\n\\t{port}\\n    '" != "if
1:\n    x = f'{host}\\n\\t{port}\\n'"
if 1:
-     x = f'{host}\n\t{port}\n    '?
----
+     x = f'{host}\n\t{port}\n'
```
Which is exactly the problem.
This fixes parsing issues with many of Python 3.7's stdlib. Namely the
following ones:
/usr/lib/python3.7/warnings.py
/usr/lib/python3.7/netrc.py
/usr/lib/python3.7/test/test_embed.py …

Fix string parsing with newline

---

.travis.yml
AUTHORS
astor/code_gen.py
docs/changelog.rst
tests/test_code_gen.py
tox.ini

This PR adds `SourceGenerator.visit_Constant` to handle Python 3.8 deprecating older constant AST node types. I reused a lot of the logic from the exist node types by breaking them out into private handlers for the node value. For a few of the node types this ended up being a little gnarly, so let me know if you have some other ideas for how to organize this code. I didn't want to duplicate a lot of the functionality, since there was a lot there (especially for strings and numeric types) that was probably learned with a lot of bug reports.
I'm not sure exactly how easily you can test this _specific_ code until the Python compiler is emitting these constant nodes directly, but I'm happy to look into it more if you'd like. Locally (at least) the existing tests were passing for me.
Fixes …

Handle new ast.Constant node in SourceGenerator

---

.gitignore
setup.cfg
tests/check_astunparse.py
tests/check_expressions.py

I'm trying to build an RPM package for astor (well, really I'm trying to build a package for Hy) and I came across a few issues during packaging that are fixed here. Mostly the relative imports should use the explicit "from ." syntax so they work outside of a pipenv.
I still get some test failures when trying to build astor but I think they're unrelated to packaging issues.

Fix various packaging issues

---

astor/code_gen.py
astor/op_util.py
docs/changelog.rst
tests/test_code_gen.py

This is a quick-'n'-dirty attempt at #126. (Closes #126.)

Add assignment expressions

---

astor/tree_walk.py
docs/changelog.rst
tests/test_misc.py

Fixes https://github.com/berkerpeksag/astor/issues/136

Fix for issue #136

---

astor/code_gen.py
astor/op_util.py
docs/changelog.rst
tests/test_code_gen.py

set precedence on f-string expressions

---

astor/code_gen.py
docs/changelog.rst
tests/test_misc.py

I believe this is just a bug. If `source_generator_class` is a class, then `isinstance` is not appropriate since it's a class, not a class instance/object.

Use issubclass instead of isinstance to compare SourceGenerator in to_source

---

astor/source_repr.py
docs/changelog.rst
tests/test_misc.py

It doesn't work for unicodes in Python 2.

Don't use str.find

---

astor/code_gen.py
docs/changelog.rst
tests/test_code_gen.py

Corresponding test also checks type annotation for parameters and assignment are pep8 friendly.

Add space around "->" to make source pep8 friendly

---

astor/file_util.py
docs/changelog.rst
tests/test_code_to_ast.py

The line number can be inconsistent between the codeobj and a FunctionDef.
Fixes #174.

Use the codeobj name in the key rather than the line number

---

astor/code_gen.py

The docstring of `SourceGenerator` in `code_gen.py` mentions a `node_to_source` functions, which doesn't seem to exist in this repository. Is this meant to be a reference to the `to_source` function instead?

Change `node_to_source` to `to_source`.

---

tests/test_code_gen.py

Int was above limits:
https://docs.python.org/3/library/stdtypes.html#int-max-str-digits

Reduce huge int in test (Closes: #212)

---

astor/code_gen.py
docs/changelog.rst
tests/test_code_gen.py

Add type parameter syntax support [PEP-695](https://peps.python.org/pep-0695/)
```python
type A = int
def f[T](value: T) -> T:
return value
```
It works above and below 3.12.
Please let me know if anything should be added/adjusted.

Add support for PEP 695 – Type Parameter Syntax

---

astor/code_gen.py
docs/changelog.rst
tests/test_code_gen.py

Add [TryStar](https://docs.pyth.onl/ja/3.13/library/ast.html#ast.TryStar) support [PEP 654 – Exception Groups and except*](https://peps.python.org/pep-0654/) [clause except*](https://docs.python.org/3/reference/compound_stmts.html#except-star) (3.11~)
```python
try:
pass
except* Exception:
pass
```
It works above and below 3.11!
Please let me know if anything should be added/adjusted.
tasks

Add support for except* syntax (PEP 654)
