berkerpeksag/astor

astor/codegen.py
(From discussion with @pmaupin on #21.)
=> revise coding style in matter of async variants of `def`, `for`, and `with`

astor/codegen.py, tests/test_codegen.py
This is a partial replacement for pull request #25.  It fixes the found codegen bugs described in issue #27, and is rebased nicely off the current master.
I will withdraw pull request #25 and figure out a better way to add the anti8 tool, and submit a new pull request for that.
=> Fixes and testcases for issue #27

README.rst
Some background for this proposed edit is here:
https://github.com/CensoredUsername/codegen/commit/f88a740cf03ecabba0e79f9b56e4258a7ce3d3de#commitcomment-11781695
Thanks,
Pat
=> Add information about other codegen derivatives

tests/test_code_gen.py
Issue #45 appears to claim that elif statements are not working.  This PR adds a test that shows that they do indeed work under some situations, so issue #45 requires that this test be transmogrified into a failing example -- otherwise I haven't a clue what needs fixing.
=> Add test for elif

CHANGES, astor/code_gen.py, tests/test_code_gen.py
It's a bit ugly, but hey, it works, right? ;)
=> Add support for f-strings

CHANGES, astor/code_gen.py, tests/test_code_gen.py
PR AMBUSH!!! ;)
This + #54 + #56 all amount to full Python 3.6 support.
=> Add support for async comprehensions

astor/code_gen.py, tests/test_code_gen.py
- also run extended test cases via `astor.rtrip`
- add regression tests for new features based on `rtrip` failures
- fix failing regressions
=> Clean up recent commits

astor/code_gen.py, tests/test_code_gen.py
New regression test and top-level tree nodes to make it work.
=> Add support for ASTs compiled with single or eval options

docs/index.rst
Make docs work at both github and rtfm.
=> Dual docs -- issue #63

astor/code_gen.py, astor/string_repr.py, tests/test_code_gen.py
-- This only affects a very few modules that did not roundtrip properly
=> Add support for __future__ unicode_literals

.travis.yml, astor/__init__.py, docs/changelog.rst, tests/support.py, tests/test_misc.py, tox.ini
=> Restore backwards compatibility that was broken after 0.6.1

README.rst
=> Use HTTPS over HTTP in readme

.travis.yml, astor/code_gen.py, docs/changelog.rst
=> Don't use 'async' as a keyword argument

AUTHORS, astor/code_gen.py, docs/changelog.rst, tests/test_code_gen.py
=> Improve codegen with NaN, infinity, and complex numbers

astor/code_gen.py, docs/changelog.rst, tests/test_code_gen.py
=> Generate correct code for empty sets

astor/code_gen.py, docs/changelog.rst, tests/test_code_gen.py
=> Fix code generation with escaped braces in f-strings

astor/code_gen.py, docs/changelog.rst, tests/test_code_gen.py
=> Fix code generation with very large integers

astor/code_gen.py, docs/changelog.rst, tests/test_code_gen.py
Add fstring debugging support
Fixes #138
=> Add fstring debugging support

setup.cfg
Run tests under nose in python setup.py test
Fixes #131
=> Run tests under nose in python setup.py test

astor/code_gen.py, docs/changelog.rst, tests/test_code_gen.py
Add match statement support, supersedes #195.
Fixes #215.
Please let me know if anything should be added/adjusted.
=> Add support for match statement
